---
#

- hosts: all
  remote_user: vagrant
  vars:
    clientHome: "{{ lookup('vars', ansible_limit + '_vars').clientHome }}"
    serviceHostPort: "{{ lookup('vars', ansible_limit + '_vars').serviceHostPort }}"
    appHostPort: "{{ lookup('vars', ansible_limit + '_vars').appHostPort }}"

  roles:
    - tomcat



...
