---
#playbook

- hosts: all
  remote_user: vagrant
  gather_facts: no
  vars:
    clientHome: "{{ lookup('vars', ansible_limit + '_vars').clientHome }}"
    serviceHostPort: "{{ lookup('vars', ansible_limit + '_vars').serviceHostPort }}"
    appHostPort: "{{ lookup('vars', ansible_limit + '_vars').appHostPort }}"

  tasks:
    - name: "Show vars for {{ ansible_limit }}"
      debug:
        msg: "{{ inventory_hostname }} - {{ clientHome }} {{ serviceHostPort }} {{ appHostPort }}"



...
